  /// \file Detector.cc
/*
 *
 * Detector.cc source template generated by fclass
 * Creation date : mer. juin 12 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#include "Detector/Detector.hh"

using namespace std;

namespace baboon {

	Detector::Detector( const std::string &detName , const DetectorType type  )
		: detectorName(detName),
		 detectorType(type),
		 isBuilt(false) {}


	Detector::~Detector() {

		detectorVolumes.clear();
	}


}  // namespace 

