  /// \file AnalogicCaloHit.cc
/*
 *
 * AnalogicCaloHit.cc source template generated by fclass
 * Creation date : mer. juin 12 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#include "Objects/AnalogicCaloHit.hh"

namespace baboon {

	AnalogicCaloHit::AnalogicCaloHit()
		: CaloHit(fAnalogicCaloHit) {

	}

	AnalogicCaloHit::~AnalogicCaloHit() {

	}


	Return AnalogicCaloHit::SetEnergy( const double &e ) {

		if( e < 0 )
			return BABOON_INVALID_PARAMETER("Energy < 0");
		energy = e;
		return BABOON_SUCCESS();
	}


	Return AnalogicCaloHit::SetEnergyError( const double &eError ) {

		if( eError < 0 )
			return BABOON_INVALID_PARAMETER("Energy error < 0");
		energyError = eError;
		return BABOON_SUCCESS();
	}


}  // namespace 

