  /// \file DigitalCaloHit.cc
/*
 *
 * DigitalCaloHit.cc source template generated by fclass
 * Creation date : mer. juin 12 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#include "Objects/DigitalCaloHit.hh"

namespace baboon {

	DigitalCaloHit::DigitalCaloHit()
		: CaloHit( fDigitalCaloHit ) {

	}

	DigitalCaloHit::~DigitalCaloHit() {

	}


}  // namespace 

