  /// \file Globals.hh
/*
 *
 * Globals.hh header template generated by fclass
 * Creation date : dim. avr. 28 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef GLOBALS_HH
#define GLOBALS_HH

#include <set>
#include <string> 
#include <vector>
#include <ostream>


namespace baboon {

	typedef std::set<std::string> StringSet;
	typedef std::vector<std::string> StringVector;
	typedef std::vector<int> IntVector;
	typedef std::vector<float> FloatVector;
	typedef std::vector<double> DoubleVector;
	typedef std::vector<bool> BoolVector;


	template <typename T>
	std::vector<T> operator +( std::vector<T> &vec1 , std::vector<T> &vec2 ) {

		std::vector<T> vec;
		for( unsigned int i=0 ; i<vec1.size() ; i++ ) vec.push_back( vec1.at(i) );
		for( unsigned int i=0 ; i<vec2.size() ; i++ ) vec.push_back( vec2.at(i) );
		return vec;
	}

	template <typename T>
	std::ostream& operator <<( std::ostream &out , std::vector<T> &vec ) {

		if( !vec.empty() ) {
			out << vec.at(0);
			for( unsigned int i=1 ; i<vec.size() ; i++ )
				out << " " << vec.at(i);
		}
		return out;
	}

}  // namespace 

#endif  //  GLOBALS_HH
