  /// \file Internal.cc
/*
 *
 * Internal.cc source template generated by fclass
 * Creation date : sam. mai 25 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#include "Utilities/Internal.hh"

namespace baboon {





}  // namespace 

