  /// \file AlgorithmHeaders.hh
/*
 *
 * AlgorithmHeaders.hh header template generated by fclass
 * Creation date : dim. avr. 28 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef ALGORITHMHEADERS_HH
#define ALGORITHMHEADERS_HH

/*!
 *
 *  @brief : All algorithm headers
 *
 */


#include "Algorithm/AbstractAlgorithm.hh"

#include "Algorithm/Tracking/HoughTransformAlgorithm.hh"
#include "Algorithm/Clustering/ClusteringAlgorithm.hh"
#include "Algorithm/Clustering/DistanceAgglomerationAlgorithm.hh"
#include "Algorithm/Clustering/CoreFinderAlgorithm.hh"
#include "Algorithm/ConeBeginningAlgorithm.hh"
#include "Algorithm/IsolationTaggingAlgorithm.hh"
#include "Algorithm/PrincipalComponentAnalysis.hh"




#endif  //  ALGORITHMHEADERS_HH
