/*
 *
 * AnalysisManager.cc cpp file template generated by fclass
 * Creation date : Mon Mar 18 21:07:41 2013
 * Copyright (c) CNRS / IPNL
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#include "Managers/AnalysisManager.hh"



using namespace std;



namespace sdhcal {




	AnalysisManager *AnalysisManager::instance = NULL;



	AnalysisManager::AnalysisManager() {

		rootOutputFile = 0;
	}



	AnalysisManager::~AnalysisManager() {}


	AnalysisManager *AnalysisManager::GetInstance() {
		if(instance == NULL) instance = new AnalysisManager();
		return instance;
	}



	void AnalysisManager::Kill() {
		if(instance != NULL) {
			delete instance;
			instance = NULL;
		}
	}


	void AnalysisManager::Init() {

		rootOutputFile = TFile::Open( outputFileName.c_str() ,"RECREATE" );

	}




	void AnalysisManager::End() {

		rootOutputFile->cd();
		rootOutputFile->Write();
		rootOutputFile->Close();
		delete rootOutputFile;
	}


}
