  /// \file BasicDraw.hh
/*
 *
 * BasicDraw.hh header template generated by fclass
 * Creation date : ven. mai 3 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef BASICDRAW_HH
#define BASICDRAW_HH

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

#include "TROOT.h"
#include "TStyle.h"
#include "TPaveText.h"
#include "TString.h"
#include "TGraph.h"
#include "TLegend.h"

namespace baboon {


	/*!
	 *
	 * brief CALICE style for CALICE plot convention
	 *
	 */
	void CaliceStyle();

	/*!
	 *
	 * @brief Draw a pave text with some conventions...
	 *
	 */
	TPaveText *DrawText( TString string );

	/*!
	 *
	 * @brief TGraph Factory
	 *
	 */
	TGraph *NewTGraph( unsigned int nbOfPts , unsigned int colorLineID );

	/*!
	 *
	 * @brief TGraph Factory
	 *
	 */
	TGraph *NewTGraph( unsigned int nbOfPts , double *x , double *y , unsigned int colorLineID );

	/*!
	 *
	 * @brief TLegend Factory
	 *
	 */
	TLegend *NewTLegend( double x1 , double y1 , double x2 , double y2 );



}  // namespace 

#endif  //  BASICDRAW_HH
