  /// \file Core.hh
/*
 *
 * Core.hh header template generated by fclass
 * Creation date : lun. avr. 29 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef CORE_HH
#define CORE_HH

#include "RecoObject.hh"

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

namespace baboon {

/* 
 * Class Core
 * Inherits from base class RecoObject
 */ 

class Core : public RecoObject {

  public:
    /*! Default Constructor */
    Core();
    /*! Default Destructor */
    virtual ~Core();

  protected:


};  // class 

}  // namespace 

#endif  //  CORE_HH
