  /// \file RecoHit.hh
/*
 *
 * RecoHit.hh header template generated by fclass
 * Creation date : lun. avr. 29 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef RECOHIT_HH
#define RECOHIT_HH

#include "RecoObject.hh"

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

namespace baboon {

/* 
 * Class RecoHit
 * Inherits from base class RecoObject
 */ 

class RecoHit : public RecoObject {

  public:
    /*! Default Constructor */
    RecoHit();
    /*! Default Destructor */
    virtual ~RecoHit();

  protected:


};  // class 

}  // namespace 

#endif  //  RECOHIT_HH
