  /// \file BaboonMainFrame.cc
/*
 *
 * BaboonMainFrame.cc source template generated by fclass
 * Creation date : lun. mai 6 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#include "Gui/BaboonMainFrame.hh"

namespace baboon {

	BaboonMainFrame::BaboonMainFrame()
		: TGMainFrame( gClient->GetRoot() , 1000 , 400 ) {

		eventNavigator = new EventNavigator( this );
		lcReader = IOIMPL::LCFactory::getInstance()->createLCReader();

	}

	BaboonMainFrame::~BaboonMainFrame() {

		delete eventNavigator;
	}




}  // namespace 

