/*
 *
 * Numeric.hh header template generated by fclass
 * Creation date : Fri Mar 15 14:10:39 2013
 * Copyright (c) CNRS / IPNL
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#ifndef NUMERIC_HH
#define NUMERIC_HH

#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>
#include <vector>
#include <utility>
#include <numeric>

namespace baboon {

	double square(double x, double y);

	std::pair<double,double> linearRegression( std::vector<double>& x , std::vector<double>& y );

	double gauss2D(double *x, double *par);

	double doubleGauss2D(double *x, double *par);
}

#endif  // NUMERIC_HH
