  /// \file AnalogicCaloHit.hh
/*
 *
 * AnalogicCaloHit.hh header template generated by fclass
 * Creation date : mer. juin 12 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef ANALOGICCALOHIT_HH
#define ANALOGICCALOHIT_HH

#include "Objects/CaloHit.hh"

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

namespace baboon {

	/*
	 * Class AnalogicCaloHit
	 * Inherits from base class CaloHit
	 */

	class AnalogicCaloHit : public CaloHit {

		public:

			/*!
			 *
			 * Default Constructor
			 *
			 */
			AnalogicCaloHit();

			/*!
			 *
			 * Default Destructor
			 *
			 */
			virtual ~AnalogicCaloHit();

			/*!
			 *
			 *
			 *
			 */
			Return SetEnergy( const double &e );

			/*!
			 *
			 *
			 *
			 */
			Return SetEnergyError( const double &eError );

		protected:

			double energy;
			double energyError;

		public:

			inline double GetEnergy() const
				{ return energy; }

			inline double GetEnergyError() const
				{ return energyError; }


	};  // class

}  // namespace 

#endif  //  ANALOGICCALOHIT_HH
