  /// \file DigitalCaloHit.hh
/*
 *
 * DigitalCaloHit.hh header template generated by fclass
 * Creation date : mer. juin 12 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef DIGITALCALOHIT_HH
#define DIGITALCALOHIT_HH

#include "CaloHit.hh"

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

namespace baboon {

	/*
	 * Class DigitalCaloHit
	 * Inherits from base class CaloHit
	 */

	class DigitalCaloHit : public CaloHit {

		public:

			/*!
			 *
			 * Default Constructor
			 *
			 */
			DigitalCaloHit();

			/*!
			 *
			 * Default Destructor
			 *
			 */
			virtual ~DigitalCaloHit();

		protected:


	};  // class

}  // namespace 

#endif  //  DIGITALCALOHIT_HH
