  /// \file EnergyCalculator.cc
/*
 *
 * EnergyCalculator.cc source template generated by fclass
 * Creation date : ven. mai 24 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#include "Reconstruction/EnergyCalculator.hh"

using namespace std;

namespace baboon {

	EnergyCalculator::EnergyCalculator() {

		energy = 0.0;
		hitCollection = 0;
		params = 0;
	}

	EnergyCalculator::~EnergyCalculator() {

	}


}  // namespace 

