/*
 *
 * HitManager.hh header template generated by fclass
 * Creation date : Wed Mar 20 18:19:39 2013
 * Copyright (c) CNRS / IPNL
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#ifndef HITMANAGER_HH
#define HITMANAGER_HH

#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>
#include <algorithm>


// baboon includes
#include "Objects/HitCollection.hh"
#include "Geometry/Matrix3D.hh"
#include "Config/SdhcalConfig.hh"
#include "Utilities/Globals.hh"
#include "Utilities/ReturnValues.hh"



namespace baboon {

	/*!
	 * Class HitManager.
	 */

	class HitManager {

		protected :
			/*! Default Constructor */
			HitManager() ;
			/*! Default Destructor */
			virtual ~HitManager() ;

			static HitManager *instance;

			HitCollection *hitCollection;

			IntVector nbOfPadsXYZ;

			DoubleVector padsSize;

			DoubleVector interpadSize;

			double layerThickness;

			Matrix3D<Hit*> hitMapVolumePtr;

		public :

			static HitManager *GetInstance();

			static void Kill();

			Return RegisterNewHit( const HitParameters &params );

			Return DeleteHit( Hit *hit );

			Return ClearAllContent();

			void BuildVolumeMap();

//			void BeginOfEvent( EVENT::LCCollection* );

//			void EndOfEvent();

			bool PadIsTouched( unsigned int I , unsigned int J , unsigned int K );

			inline HitCollection *GetHitCollection()
				{ return hitCollection; }

			Matrix3D<Hit*> GetHitCubeAt( unsigned int I, unsigned int J, unsigned int K, unsigned int size);

//			EVENT::CalorimeterHitVec *GetCalorimeterHitCollection();

			Hit *GetHitAt( unsigned int I , unsigned int J , unsigned int K );

			DoubleVector PositionToIJK( const ThreeVector& v );

//			static HitCollection *GetNewHitCollection( EVENT::LCCollection* lcCol );

			bool PadExists( int I , int J , int K );


	};

}

#endif  // HITMANAGER_HH
