  /// \file TreeProcessor.hh
/*
 *
 * TreeProcessor.hh header template generated by fclass
 * Creation date : ven. mai 3 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef TREEPROCESSOR_HH
#define TREEPROCESSOR_HH

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

#include "Analysis/InputTreeWrapper.hh"

#include "TH1D.h"


namespace baboon {


	typedef struct {

		double contamination1;
		double contamination2;
		double purity1;
		double purity2;
		double algorithmEfficiency;

	} EstimatorVars;



	/*!
	 * Class TreeProcessor
	 */

	class TreeProcessor {

	public:

		/*! Default Constructor */
		TreeProcessor( TTree* );

		/*! Default Destructor */
		virtual ~TreeProcessor();

		void Loop();

		inline EstimatorVars GetMeans()
			{ return estimatorMeans; }


	protected:

		InputTTreeWrapper *treeWrapper;

		EstimatorVars estimatorMeans;



	};  // class

}  // namespace 

#endif  //  TREEPROCESSOR_HH
