  /// \file CaloHitCreator.hh
/*
 *
 * CaloHitCreator.hh header template generated by fclass
 * Creation date : jeu. mai 9 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef CALOHITCREATOR_HH
#define CALOHITCREATOR_HH


#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

#include "EVENT/LCEvent.h"
#include "UTIL/CellIDDecoder.h"
#include "EVENT/CalorimeterHit.h"

#include "Utilities/ReturnValues.hh"
#include "Utilities/Globals.hh"
#include "Utilities/Internal.hh"
#include "Objects/HitCollection.hh"
#include "Managers/HitManager.hh"


namespace baboon {

	/*
	 * Class CaloHitCreator
	 */

	class CaloHitCreator {

		public:

			class ThresholdUndefinedException{};

			/*! Default Constructor */
			CaloHitCreator();

			/*! Default Destructor */
			virtual ~CaloHitCreator();


			baboon::Return CreateCaloHits( EVENT::LCEvent * );



		protected:

			std::string collectionName;
			std::string decoderString;
			StringVector IJKEncoding;
			baboon::HitCollection *hitCollection;

		public :
			void SetCollectionName( const std::string &colName )
				{ collectionName = colName; }

			void SetDecoderString( const std::string &decoderStr )
				{ decoderString = decoderStr; }

			Return SetIJKEncoding( const StringVector &ijkEnco );


	};  // class

}

#endif  //  CALOHITCREATOR_HH
